version: '3.5'

services:

  daemon:
    container_name: playstation_discord
    build:
      context: .
    restart: always
    command: python -u main.py
    env_file: config.env
    environment:
      CONFIG: ./config/cobra-bot.yml
